import React, { useContext, useState } from "react"
import Head from "next/head"

import Context from "../components/Context"

import MyMap from "../components/MyMap"
import MySearchBar from "../components/MySearchBar"
import MyBoard from "../components/MyBoard"

export default function Home() {
  const [toggle, setToggle] = useState(false)
  const { ip } = useContext(Context)

  const handleOnClickInfo = () => {
    console.log("plop")
  }

  return (
    <div>
      <Head>
        <title>IP tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex flex-col">
        <MySearchBar
          onClickInfo={() => (toggle ? setToggle(false) : setToggle(true))}
        />

        <div
          className="hidden md:flex w-full absolute  justify-center"
          style={{
            transform: "translateY(150%)",

            zIndex: 10,
          }}>
          <MyBoard />
        </div>
        <div className="flex md:hidden w-full justify-center">
          {toggle ? <MyBoard /> : null}
        </div>
        <MyMap />
      </main>
    </div>
  )
}
