import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import MyMap from './components/MyMap'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1 className="text-3xl font-bold underline text-gray-400"> Hello world!</h1>
      <MyMap />
      </main>
      <footer className={styles.footer}>
      </footer>
      
    </div>
  )
}


