import Head from "next/head"
import styles from "../styles/Home.module.css"

import MyMap from "../components/MyMap"
import SearchBar from "../components/SearchBar"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SearchBar />
        <MyMap />
      </main>
      <footer className={styles.footer}></footer>
    </div>
  )
}
